### ISSUE TITLE
Preserve the order of field names in the array to allow renaming via field index numbers

### ISSUE THREAD

**Issue by martwo** [icecube/skyllh#101]
The field name list should reflect and keep the order of field names. So fields can be addressed also by field indices. This would make the field name renaming easier for the user after loading a table data file.
Hence, the dictionary for the field renaming method could have integer numbers as keys addressing field by index.
This requires that the _field_name_list property will preserve the order of field names thoughout the code of the DataFieldRecordArray class.
https://github.com/icecube/skyllh/blob/d99e35e6de3a4b9ed1b5849cd7483bb229a5dfd1/skyllh/core/storage.py#L895

**Comment by tomaskontrimas** [comment]
It's probably better to be explicit in the field renaming and not rely on indices
