### ISSUE TITLE
Lower bin index might not have to be incremented by 1

### ISSUE THREAD

**Issue by martwo** [icecube/skyllh#107]
The bin edges are taking directly from the Aeff enu binedges. So in lower bin index should be correct. Hence, there should NOT be the need to increment the lidx by 1.

https://github.com/icecube/skyllh/blob/a41ad072c278c13639acc2285c8f5e2ea9d16dee/skyllh/analyses/i3/publicdata_ps/pd_aeff.py#L334

**Comment by chiarabellenghi** [comment]
I believe this has been solved by commit https://github.com/icecube/skyllh/commit/b1981dc05499e9f72f6c6db4c5412d0282dc1a4c
