### ISSUE TITLE
Speed up initial analysis setup

### ISSUE THREAD

**Issue by tomaskontrimas** [icecube/skyllh#129]
There is potential for ~53% speedup when creating analysis (detector signal yields).

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/52071038/227748914-a5f81163-9b8b-4b0b-ab56-49a90c9e4749.png">

We could sort `data_sin_true_dec` once, pass `idxs` to `hist` function and apply them to `data_sin_true_dec`, `data_true_energy` and `weights`.

https://github.com/icecube/skyllh/blob/a5c6185fa25dcdc46dca0084296282ba226a3542/skyllh/i3/detsigyield.py#L643
https://github.com/icecube/skyllh/blob/a5c6185fa25dcdc46dca0084296282ba226a3542/skyllh/i3/detsigyield.py#L613

**Comment by chiarabellenghi** [comment]
Can we close this issue? 😃

**Comment by martwo** [comment]
It will be closed automatically once I merge the parameter_handling branch!
