### ISSUE TITLE
Update import of the `create_analysis` method

### ISSUE THREAD

**Issue by chiarabellenghi** [icecube/skyllh#136]
Update import of the `create_analysis` method in the public data tutorial notebook https://github.com/icecube/skyllh/blob/publicdata_ps/doc/sphinx/tutorials/publicdata_ps.ipynb

**Comment by tomaskontrimas** [comment]
Fixed in https://github.com/icecube/skyllh/commit/e698970aa3209cdc4d700bbb69a1ca0f750aef3a
