### ISSUE TITLE
`PDSignalGenerator` does not support multiple sources

### ISSUE THREAD

**Issue by tomaskontrimas** [icecube/skyllh#140]
In case of multiple sources at different declinations in the same source hypothesis group, the cached `self.effA` object would be reused in signal generator, producing an incorrect result.

https://github.com/icecube/skyllh/blob/1e047b1f5557cd357fd9a40a904f305e6c72203b/skyllh/analyses/i3/publicdata_ps/signal_generator.py#L596-L601

Should raise an error if `shg.source_list` and `shg_list` lengths are not equal to 1.

**Comment by chiarabellenghi** [comment]
Actually, I would like to include support for the stacking analysis. I'll label this as WP

**Comment by martwo** [comment]
@chiarabellenghi Are you actively working in this? I would propose to add a check for the number of sources and raise an error if there is more than 1 source defined in the src_hypo_group_manager. When adapting the code for SkyLLH2 we can fix this then.
