### ISSUE TITLE
test_analysis.py needs work

### ISSUE THREAD

**Issue by chrhck** [icecube/skyllh#15]
https://github.com/IceCubeOpenSource/skyllh/blob/7ef48aa53b6c01cc2f5eba62e3c22d9fa8d732ae/tests/core/test_analysis.py#L46

**Comment by chrhck** [comment]
also "'detsigeff_implmethod", "fluxmodel" and "sig_gen_method" are undefined

**Comment by chrhck** [comment]
`./tests/core/test_analysis.py:46:13: F821 undefined name 'source'
            source, fluxmodel, detsigeff_implmethod, sig_gen_method))
            ^
./tests/core/test_analysis.py:46:21: F821 undefined name 'fluxmodel'
            source, fluxmodel, detsigeff_implmethod, sig_gen_method))
                    ^
./tests/core/test_analysis.py:46:32: F821 undefined name 'detsigeff_implmethod'
            source, fluxmodel, detsigeff_implmethod, sig_gen_method))
                               ^
./tests/core/test_analysis.py:46:54: F821 undefined name 'sig_gen_method'
            source, fluxmodel, detsigeff_implmethod, sig_gen_method))
                                                     ^
./tests/core/test_analysis.py:49:62: F821 undefined name 'rss'
        src_fitparam_mapper = SingleSourceFitParameterMapper(rss)
                                                             ^
./tests/core/test_analysis.py:50:47: F821 undefined name 'fitparam_gamma'
        src_fitparam_mapper.def_fit_parameter(fitparam_gamma)
                                              ^
./tests/core/test_analysis.py:59:26: F821 undefined name 'DataScrambler'
        data_scrambler = DataScrambler(UniformRAScramblingMethod(),
                         ^
./tests/core/test_analysis.py:59:40: F821 undefined name 'UniformRAScramblingMethod'
        data_scrambler = DataScrambler(UniformRAScramblingMethod(),
                                       ^
./tests/core/test_analysis.py:63:26: F821 undefined name 'FixedScrambledExpDataI3BkgGenMethod'
        bkg_gen_method = FixedScrambledExpDataI3BkgGenMethod(data_scrambler)
                         ^
2     E999 SyntaxError: invalid syntax`

**Comment by martwo** [comment]
This unit test is very out of date. The entire interface has probably changed since then. This entire test should probably be rewritten from scratch.

**Comment by chrhck** [comment]
Okay, I'll tell flake8 to ignore the file for now
