### ISSUE TITLE
Lots of arguments are missing in the argument parser.

### ISSUE THREAD

**Issue by chiarabellenghi** [icecube/skyllh#160]
https://github.com/icecube/skyllh/blob/f0216c4017f6c0f97aa32018b108e5d136d9f78e/skyllh/analyses/i3/publicdata_ps/time_integrated_ps.py#L481C6-L488

**Comment by martwo** [comment]
The extra (standard) argument options are defined here: https://github.com/icecube/skyllh/blob/f0216c4017f6c0f97aa32018b108e5d136d9f78e/skyllh/scripting/argparser.py#L43
