### ISSUE TITLE
assert_is_valid_for_exp_data doesn't seem to to anything

### ISSUE THREAD

**Issue by chrhck** [icecube/skyllh#19]
It seems like:
https://github.com/IceCubeOpenSource/skyllh/blob/7ef48aa53b6c01cc2f5eba62e3c22d9fa8d732ae/skyllh/i3/pdf.py#L168

doesn't actually perform an assert?

**Comment by martwo** [comment]
The method assert_is_valid_for_exp_data is deprecated. Instead the assert_is_valid_for_trial_data should be used.
