### ISSUE TITLE
Fix in poissonian # of signal events generated for Public Data

### ISSUE THREAD

**Issue by juanma-cano-vila** [icecube/skyllh#223]
There is a bug in the current implementation of the Poissonian # of signal events generated in the public data signal generator PDDatasetSignaGenerator.

In the current implemetation we have:

https://github.com/icecube/skyllh/blob/53461a668900fa73f615310a67dc86f285d2e8d9/skyllh/analyses/i3/publicdata_ps/signal_generator.py#L507-L516

This rewrites the variable n_events, making the possion option irrelevant. To fix it, we just have to change the first n_events in line 508 by mean, so if we have the poisson option activated the n_events comes from it.

``` 
if poisson: 
     mean = rss.random.poisson( 
         float_cast( 
             mean, 
             'The  'mean' argument must be castable to type of float!')) 
 
n_events = int_cast( 
     mean, 
     'The 'mean' argument must be castable to type of int!') ```

**Comment by chiarabellenghi** [comment]
Good catch. You can just add an `else` statement:

```
if poisson: 
     mean = rss.random.poisson( 
         float_cast( 
             mean, 
             'The  'mean' argument must be castable to type of float!')) 
 
else:
     n_events = int_cast( 
          mean, 
          'The 'mean' argument must be castable to type of int!') ```
