### ISSUE TITLE
gamma interpolation: performance

### ISSUE THREAD

**Issue by HansN87** [icecube/skyllh#4]
current implementation interpolates spatial and energy pdfs separately.
we could potentially gain a factor of ~2 speedup by interpolating the product directly.

**Comment by HansN87** [comment]
related to https://github.com/IceCubeOpenSource/skyllh/issues/38

**Comment by martwo** [comment]
It has been found that the external gamma interpolation is faster than the internal photospline interpolation with 4D KDE PDFs.
