### ISSUE TITLE
ability to calculate different test-statistics (not involving background hypo)

### ISSUE THREAD

**Issue by HansN87** [icecube/skyllh#40]
to better test the description of our signal pdfs we need to be able to calculate test-statistics of the form

case1 (H0: ns = ns0, H1: ns != ns0)
TS1 = log L(ns=ns0, gamma=const)- log L(ns=ns_best, gamma=const)

case2 (H0: gamma = gamma0, H1: gamma != gamma0)
TS2 = log L(ns=const, gamma=gamma0)- log L(ns=const, gamma=gamma_best)

i.e. tests involving only the parameters of the signal hypo in both hypotheses and reduced to a 1D problem.

**Comment by HansN87** [comment]
also case3 (H0:gamma=gamma0, ns=ns0 and H1: gamma!=gamma0, ns!=ns0)
TS3 =  log L(ns=ns0, gamma=gamma0)- log L(ns=ns_best, gamma=gamma_best)

**Comment by martwo** [comment]
This should be doable easily within the SkyLLH2 framework, where parameters can be changed from fixed to fit parameters and vise versa.
