### ISSUE TITLE
investigate when bkg pdf becomes 0 in KDE PDF.

### ISSUE THREAD

**Issue by HansN87** [icecube/skyllh#44]
https://github.com/IceCubeOpenSource/skyllh/blob/9c7695e02f04648a5cfb138d459b7f95530edba0/skyllh/core/pdfratio.py#L732

**Comment by martwo** [comment]
One could add a logger.warning() when ever there are events with background PDF values of zero.

**Comment by HansN87** [comment]
yes - and probably introduce an epsilon floor. I am thinking of rare high energy events. 
It would be a shame if such events were not to contribute because their S/B being nan.
