### ISSUE TITLE
Unstable psi angle using arccos

### ISSUE THREAD

**Issue by tomaskontrimas** [icecube/skyllh#82]
See description in https://github.com/IceCubeOpenSource/i3skyllh/issues/59#issuecomment-740016108

Found in the following files:
https://github.com/IceCubeOpenSource/skyllh/blob/master/skyllh/core/signalpdf.py#L116
https://github.com/IceCubeOpenSource/skyllh/blob/master/skyllh/core/coords.py#L31

**Comment by tomaskontrimas** [comment]
It would be nice to replace https://github.com/icecube/skyllh/blob/0cab4fb50737b3576645f993e5e55bdc4dd4dc44/skyllh/core/coords.py#L31-L37 calculation with the new `angular_separation` function introduced in [parameter_handling](https://github.com/icecube/skyllh/compare/parameter_handling) branch

**Comment by martwo** [comment]
Fixed in PR #149
