### ISSUE TITLE
DatasetCollection.remove_data_preparation(.) and Dataset.remove_data_preparation(.) are not interfaced correctly

### ISSUE THREAD

**Issue by HansN87** [icecube/skyllh#83]
https://github.com/IceCubeOpenSource/skyllh/blob/c286b9a4f025952146a0e6b82dc04c04e9f07a81/skyllh/core/dataset.py#L1425
Name of default argument index is inconsistent with the one used by the same method in Dataset class (uses key instead of index -- allowing for more general use). It should be either index or key.

See https://github.com/IceCubeOpenSource/skyllh/blob/c286b9a4f025952146a0e6b82dc04c04e9f07a81/skyllh/core/dataset.py#L799

**Comment by tomaskontrimas** [comment]
Fixed in https://github.com/icecube/skyllh/commit/b02771ccc33f0e6a381bb17f004ef85d45ac3f45 and https://github.com/icecube/skyllh/commit/a9a8398d1d963387bd19c5878ef1d0595d4cc219
