### ISSUE TITLE
gradient calculation for stacking analysis has a problem

### ISSUE THREAD

**Issue by ibsafa** [icecube/skyllh#87]
pre-computed likelihood gradients in the stacking case used for minimization do not match gradients computed numerically (finite differences). minimization is still possible, but only using finite differences.

**Comment by HansN87** [comment]
just a small update: I started to dig into this by doing some tests with the KDE based likelihood implementation. I tested various stacking cases (equal weights, un-equal weights) and signal strengths. The gradient calculations look good and are well reproduced by their finite difference counterparts.
