### ISSUE TITLE
Rename costum_signal_generator parameter to signal_generator

### ISSUE THREAD

**Issue by martwo** [icecube/skyllh#97]
The custom_signal_generator parameter should be renamed to signal_generator with default value of None. If set to None the default signal generator class will be used. Otherwise this given SignalGenerator instance should be used.

https://github.com/icecube/skyllh/blob/aebfbcbf6c25598bb68062cbee6f20fbe19c60d5/skyllh/core/analysis.py#L88

**Comment by tomaskontrimas** [comment]
Closed by #112 PR.
