### ISSUE TITLE
Possible dataset weights calculation issue

### ISSUE THREAD

**Issue by tomaskontrimas** [icecube/skyllh#98]
The following loop and comments in `MultiSourceDatasetSignalWeights` seem incorrect:
https://github.com/icecube/skyllh/blob/aebfbcbf6c25598bb68062cbee6f20fbe19c60d5/skyllh/core/llhratio.py#L1118-L1127

The `detsigyield_arr` shape is:
```
self._detsigyield_arr : 2D (N_source_hypo_groups,N_datasets)-shaped ndarray of DetSigYield instances
```
and `Y` is supposed to be
```
Y = np.empty((N_datasets, len(self._src_arr_list[0])), dtype=np.float)
```

The result of loop in L1120 gets overwritten each time, therefore `Y` and `Y_grads` are only from the last `k`th source hypothesis group.

**Comment by martwo** [comment]
Fixed in PR #149
